listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=SERVER_PUBLIC_IP

realm=liveturn.islmtv.com
server-name=liveturn.islmtv.com

fingerprint
lt-cred-mech
user=weblive:CHANGE_ME_TURN_PASSWORD

cert=/etc/letsencrypt/live/liveturn.islmtv.com/fullchain.pem
pkey=/etc/letsencrypt/live/liveturn.islmtv.com/privkey.pem

min-port=49152
max-port=65535

no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1
log-file=/var/log/turnserver/turnserver.log
simple-log
